//
// Cleanup all the defines
// because they're implementation details
// that the users shouldn't have to
// care about or know about.
//

#ifdef ADRUTILS_COMPILER_TRAITS_H
#undef ARDUTILS_COMPILER_TRAITS_H
#endif

#undef COMPILER_TRAIT_HAS_NOTHROW_ASSIGN
#undef COMPILER_TRAIT_HAS_NOTHROW_COPY
#undef COMPILER_TRAIT_HAS_NOTHROW_CONSTRUCTOR

#undef COMPILER_TRAIT_HAS_TRIVIAL_ASSIGN
#undef COMPILER_TRAIT_HAS_TRIVIAL_COPY
#undef COMPILER_TRAIT_HAS_TRIVIAL_CONSTRUCTOR
#undef COMPILER_TRAIT_HAS_TRIVIAL_DESTRUCTOR

#undef COMPILER_TRAIT_HAS_VIRTUAL_DESTRUCTOR

#undef COMPILER_TRAIT_IS_ABSTRACT
#undef COMPILER_TRAIT_IS_BASE_OF
#undef COMPILER_TRAIT_IS_CLASS
#undef COMPILER_TRAIT_IS_EMPTY
#undef COMPILER_TRAIT_IS_ENUM
#undef COMPILER_TRAIT_IS_LITERAL_TYPE
#undef COMPILER_TRAIT_IS_POD
#undef COMPILER_TRAIT_IS_POLYMORPHIC
#undef COMPILER_TRAIT_IS_STANDARD_LAYOUT
#undef COMPILER_TRAIT_IS_TRIVIAL
#undef COMPILER_TRAIT_IS_UNION

#undef COMPILER_TRAIT_UNDERLYING_TYPE

#undef COMPILER_TRAIT_ALIGNOF

#undef HAS_COMPILER_TRAIT_HAS_NOTHROW_ASSIGN
#undef HAS_COMPILER_TRAIT_HAS_NOTHROW_COPY
#undef HAS_COMPILER_TRAIT_HAS_NOTHROW_CONSTRUCTOR

#undef HAS_COMPILER_TRAIT_HAS_TRIVIAL_ASSIGN
#undef HAS_COMPILER_TRAIT_HAS_TRIVIAL_COPY
#undef HAS_COMPILER_TRAIT_HAS_TRIVIAL_CONSTRUCTOR
#undef HAS_COMPILER_TRAIT_HAS_TRIVIAL_DESTRUCTOR

#undef HAS_COMPILER_TRAIT_HAS_VIRTUAL_DESTRUCTOR

#undef HAS_COMPILER_TRAIT_IS_ABSTRACT
#undef HAS_COMPILER_TRAIT_IS_BASE_OF
#undef HAS_COMPILER_TRAIT_IS_CLASS
#undef HAS_COMPILER_TRAIT_IS_EMPTY
#undef HAS_COMPILER_TRAIT_IS_ENUM
#undef HAS_COMPILER_TRAIT_IS_LITERAL_TYPE
#undef HAS_COMPILER_TRAIT_IS_POD
#undef HAS_COMPILER_TRAIT_IS_POLYMORPHIC
#undef HAS_COMPILER_TRAIT_IS_STANDARD_LAYOUT
#undef HAS_COMPILER_TRAIT_IS_TRIVIAL
#undef HAS_COMPILER_TRAIT_IS_UNION

#undef HAS_COMPILER_TRAIT_UNDERLYING_TYPE

#undef HAS_COMPILER_TRAIT_ALIGNOF

#include "CompilerDetectEnd.h"
